### ISSUE TITLE
Add a way of safely doing an upsert in CHashMap

### ISSUE THREAD

**Issue by brendanzab** [ticki/tfs#19]
I would like to be able to do something like this:

```rust
let map = CHashMap::new();

// ...

let values = vec![1, 2, 3];

match map.get_mut(&"x") {
    None => { map.insert("x", values); }
    Some(mut existing) => existing.extend(values),
}
```

I'm assuming another thread might be able to insert an entry into `map` between the time of the lookup and the call to `CHashMap::insert`. This would cause that previous entry to be discarded. It would be nice to be able to ensure this would not happen!

**Comment by arthurprs** [comment]
I guess this can implemented with the Entry api

**Comment by ticki** [comment]
Yeah, Entry API would be nice. I've added it to my list of things to do.

**Comment by ticki** [comment]
Entry API is pretty complex, and won't be completed today, but there's now a way to do upsert.

**Comment by brendanzab** [comment]
Hm, the sad thing is with the upsert API as given I would probably have to clone the `values` vector:

```
let map = CHashMap::new();

// ...

let values = vec![1, 2, 3];

map.upsert(&"x", values.clone(), |existing| {
    existing.extend(values);
});
```

**Comment by ticki** [comment]
That's a good point actually. It should take a closure instead.

**Comment by ticki** [comment]
done. `1.0.0` is on crates.io now.

**Comment by brendanzab** [comment]
Doesn't really solve the problem, because either one has to take ownership :P

```rust
// makes rustc sad:
    fn write_events<Events>(&self, aggregate_id: &Id, events: Events)
        where Events: IntoIterator<Item = Event>,
    {
        self.event_log.upsert(aggregate_id.clone(),
                              || events.into_iter().collect(),
                              |existing| existing.extend(events));
    }
```

**Comment by brendanzab** [comment]
Oh welse! Sorry for being a pain! 😭

**Comment by arthurprs** [comment]
A single FnMut(Some(&mut V)) then?

**Comment by ticki** [comment]
> Doesn't really solve the problem, because either one has to take ownership :P

Hmm, that's interesting. Moving seems a bit overkill so maybe a separate method for that?

> A single FnMut(Some(&mut V)) then?

How'd you insert with that?

**Comment by ticki** [comment]
@brendanzab 

What about

```rust
fn insert_map<F: Fn(Some(V)) -> V>(key: K, f: F)
```

**Comment by brendanzab** [comment]
What about:

```
fn alter<F: Fn(Some(V)) -> Some(V)>(key: K, f: F)
```

**Comment by ticki** [comment]
I like that.

**Comment by brendanzab** [comment]
That's what [Haskell has anyway](https://hackage.haskell.org/package/unordered-containers-0.2.7.2/docs/Data-HashMap-Strict.html#v:alter).

**Comment by brendanzab** [comment]
Update would be:

```
fn update<F: Fn(V) -> Option<V>>(key: K, f: F)
```

**Comment by brendanzab** [comment]
Should it return an `Option<V>` too?

**Comment by ticki** [comment]
Added `alter`.

**Comment by brendanzab** [comment]
Should it be `FnOnce`?

**Comment by brendanzab** [comment]
Gonna be a pain with semver now... perhaps you could 2.0 it, and remove `upsert`? 😓

**Comment by ticki** [comment]
@brendanzab It's fine. I've not removed `upsert` because I still think the ability to get a reference is useful, but they now take a `FnOnce`.
